development:
  clients:
    default:
      database: eclickr_development
      hosts:
        - 127.0.0.1:27017

test:
  clients:
    default:
     uri: <%= ENV['MONGOHQ_URL'] %>

staging:
  clients:
    default:
     uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    log_level: :warning

production:
  clients:
    default:
     # The standard MongoDB connection URI allows for easy
     # replica set connection setup.
     # Use environment variables or a config file to keep your
     # credentials safe e.g. <%= ENV['MONGODB_URI'] %>.
     uri: <%= ENV['MONGOHQ_URL'] %>
  options:
    log_level: :warning
    consistency: :eventual # is that OK?